package main

const (
	scansText = `{{define "scans"}}// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package {{.PackageName}}

import "database/sql"

{{range .Tokens -}}
func {{visible "s"}}can{{title .Name}}(r *sql.Row) (*{{.Name}}, error) {
	var s {{.Name}}
	if err := r.Scan({{range .Fields}}
		&s.{{.Name}},{{end}}
	); err != nil {
		return nil, err
	}
	return &s, nil
}

func {{visible "s"}}can{{title .Name}}s(rs *sql.Rows) ([]*{{.Name}}, error) {
	structs := make([]*{{.Name}}, 0, 16)
	var err error
	for rs.Next() {
		var s {{.Name}}
		if err = rs.Scan({{range .Fields}}
			&s.{{.Name}},{{end}}
		); err != nil {
			return nil, err
		}
		structs = append(structs, &s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

func {{visible "f"}}ields{{title .Name}}(i *{{.Name}}) []interface{} {
	o := make([]interface{},{{len .Fields}})
	{{range $i, $v := .Fields -}}
	o[{{$i}}] = i.{{$v.Name}}
	{{end -}}
	return o
}

{{$fLen := len .Fields -}}
{{$typeName := .Name -}}
var (
	{{visible "i"}}nsert{{title .Name}}Fields = "({{range $i, $v := .Fields}}{{if $i}},{{end}}{{$v.Name}}{{end}})"
	{{visible "i"}}nsert{{title .Name}}Binds = "({{range $i, $v := .Fields}}{{if $i}},{{end}}${{inc $i}}{{end}})"
	{{visible "u"}}pdate{{title .Name}}Fields = "{{range $i, $v := .Fields -}}
{{- if not $v.IsPK}}
{{- $v.Name}}=${{inc $i}}
{{- if not ( eq ( inc $i ) $fLen ) }},{{end}}
{{- end}}
{{- end}}"
	{{visible "s"}}elect{{title .Name}}Fields = "{{range $i, $v := .Fields}}{{if $i}},{{end}}{{$v.Name}}{{end}}"
	{{visible "s"}}elect{{title .Name}}FullFields = "{{range $i, $v := .Fields}}{{if $i}},{{end}}{{title $typeName}}.{{$v.Name}}{{end}}"
)

{{end -}}
{{end -}}`
)
